---
name: SlapperAllVersion
author:
- Vecnavium
- jojoe77777
- KipeCraft (Remake)
version: 1.0.0
description: SlapperAllVesion, NPC plugin for PocketMine-MP Support All Versions
main: slapper\Main
api:
- 4.0.0
- 5.0.0
mcpe-protocol:
- 569
- 567
- 565
- 563
- 562
- 561
- 560
- 559
- 558
- 557
- 555
- 554
- 553
- 552
- 551
- 545
- 544
- 543
- 542
- 534
- 533
- 532
- 530
- 527
- 526
- 524
- 516
- 514
- 512
- 503
- 498
- 497
- 495
- 491
- 490
- 486
- 485
- 479
- 477
- 476
- 475
- 474
- 471
- 465
- 464
- 462
- 459
- 456
- 455
- 453
- 448
- 441
- 440
- 437
- 435
- 434
- 433
- 431
- 430
- 429
- 428
- 427
- 425
- 424
- 423
- 422
- 421
- 420
- 419
- 418
- 417
- 416
- 415
- 414
- 413
- 412
- 411
- 410
- 409
- 408
- 407
- 406
- 405
- 404
- 403
- 402
- 401
- 400
- 396
- 395
- 394
- 393
- 392
- 391
- 390
- 389
- 388
- 387
- 386
- 385
- 372
- 371
- 370
- 361
- 360
- 354
- 353
- 352
- 351
- 350
- 340
- 332
- 331
- 330
- 313
- 312
- 311
- 310
- 291
- 290
- 282
- 281
- 280
- 274
- 273
- 271
- 270
- 261
- 260
- 240
- 224
- 223
- 222
- 221
- 220
- 201
- 200
- 160
- 150
- 141
- 140
- 137
- 136
- 135
- 134
- 133
- 132
- 131
- 130
commands:
  slapper:
    description: Create a Slapper NPC, or edit an existing one!
    usage: /slapper [args]...
    permission: slapper.create;slapper.edit;slapper.remove;slapper.id;slapper.help
  rca:
    description: Execute a command as someone else!
    usage: /rca <player> <command>
    permission: slapper.rca
  nothing:
    description: Do nothing!
    usage: /nothing
    permission: slapper.nothing
permissions:
  slapper.create:
    description: Allow using command /slapper create
    default: op
  slapper.edit:
    description: Allow editing Slapper entity data with /slapper edit
    default: op
  slapper.nothing:
    description: Allow doing nothing
    default: op
  slapper.rca:
    description: Allow running commands as other players
    default: op
  slapper.remove:
    description: Allow removing Slapper entities with /slapper remove [id]
    default: op
  slapper.id:
    description: Allow viewing entity ID
    default: op
  slapper.list:
    description: Allow viewing of a list of Entitys
    default: op
  slapper.help:
    description: Allow viewing Slapper help page
    default: op
...
